# Generated by Django 2.1.3 on 2019-05-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20190509_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='tiempo_max',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tiempo_min',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
