# Generated by Django 2.1.3 on 2019-06-03 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190509_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='tiempo',
        ),
    ]
