# Generated by Django 2.1.3 on 2019-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_remove_evaluacion_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='tiempo_max',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='tiempo_min',
        ),
        migrations.AddField(
            model_name='presentacion',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='tiempo',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tiempo_max',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tiempo_min',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
