# Generated by Django 2.1.3 on 2019-05-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20190509_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo',
            field=models.TimeField(default='00:00'),
        ),
    ]
