# Generated by Django 2.1.3 on 2019-05-10 02:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20190509_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo',
            field=models.TimeField(default=datetime.datetime(2019, 5, 10, 2, 16, 46, 714442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_max',
            field=models.TimeField(default=datetime.datetime(2019, 5, 10, 2, 16, 46, 714442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_min',
            field=models.TimeField(default=datetime.datetime(2019, 5, 10, 2, 16, 46, 714442, tzinfo=utc)),
        ),
    ]
