# Generated by Django 2.1.3 on 2019-05-10 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190509_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='tiempo_max',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='tiempo_min',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo',
            field=models.TimeField(default=datetime.datetime(2019, 5, 10, 2, 17, 23, 116321, tzinfo=utc)),
        ),
    ]
