# Generated by Django 2.1.3 on 2019-05-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_auto_20190509_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='tiempo',
        ),
    ]
